apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    {{- include "app.annotations" . | nindent 4 }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 6 }}
  template:
    {{- include "app.podTemplate" . | nindent 4 }}