apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    {{- include "app.annotations" . | nindent 4 }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  keycloak-secret: {{ .Values.keycloak.secret | b64enc | quote }}
  db-password: {{ .Values.db.password | b64enc | quote }}